# clowder server
clowder:
  image: clowder/clowder:develop
#  environment:
#    CLOWDER_ADMIN: "joe@aol.com"
#    TOOLMANAGER_URI: "http://192.168.99.100:8080"
#    SMTP_HOST: smtp.ncsa.illinois.edu
  ports:
    - "9000:9000"
  links:
    - mongo
    - rabbitmq
    - elasticsearch

# extractors
filedigest:
  image: clowder/extractors-digest
  links:
    - rabbitmq

audiopreview:
  image: clowder/extractors-audio-preview
  links:
    - rabbitmq

imagepreview:
  image: clowder/extractors-image-preview
  links:
    - rabbitmq

imagemetadata:
  image: clowder/extractors-image-metadata
  links:
    - rabbitmq

pdfpreview:
  image: clowder/extractors-pdf-preview
  links:
    - rabbitmq

videopreview:
  image: clowder/extractors-video-preview
  links:
    - rabbitmq

# mongo database used to store metadata/data
mongo:
  image: mongo:latest
  ports:
    - "27017:27017"
  # volumes:
  #   - clowder/mongo:/data/db

# rabbitmq to connect to extractors
rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
  # volumes:
  #   - clowder/rabbitmq:/var/lib/rabbitmq

# elasticsearch to allow indexing
elasticsearch:
    image: elasticsearch:2
    command: elasticsearch -Des.cluster.name="clowder"
    ports:
        - "9200:9200"
        - "9300:9300"
    # volumes:
    #     - ${PWD}/esdata:/usr/share/elasticsearch/data
